services:
  - type: web
    name: flask-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    rootDir: backend

  - type: web
    name: react-frontend
    env: static
    buildCommand: "npm install && npm run build"
    staticPublishPath: build
    rootDir: frontend
